### ISSUE TITLE
cdc-stresor failed with  index out of range [0] with length 0

### ISSUE THREAD

**Issue by aleksbykov** [piodul/cdc-stressor#1]
next schema was created:
```
[shard 0] migration_manager - Create new ColumnFamily: org.apache.cassandra.config.CFMetaData@0x600009181c00[cfId=b5d20b21-7fae-11ea-be51-000000000000,ksName=ks1,cfName=table1,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.FloatType,org.apache.cassandra.db.marshal.ByteType,org.apache.cassandra.db.marshal.TimestampType,org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType(636f6c37:org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.TimeUUIDType))),comment=,readRepairChance=0,dcLocalReadRepairChance=0.1,gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.Int32Type, org.apache.cassandra.db.marshal.ShortType, org.apache.cassandra.db.marshal.ByteType, org.apache.cassandra.db.marshal.ShortType, org.apache.cassandra.db.marshal.ShortType),minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=pk0, type=org.apache.cassandra.db.marshal.Int32Type, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=pk1, type=org.apache.cassandra.db.marshal.ShortType, kind=PARTITION_KEY, componentIndex=1, droppedAt=-9223372036854775808}, ColumnDefinition{name=pk2, type=org.apache.cassandra.db.marshal.ByteType, kind=PARTITION_KEY, componentIndex=2, droppedAt=-9223372036854775808}, ColumnDefinition{name=pk3, type=org.apache.cassandra.db.marshal.ShortType, kind=PARTITION_KEY, componentIndex=3, droppedAt=-9223372036854775808}, ColumnDefinition{name=pk4, type=org.apache.cassandra.db.marshal.ShortType, kind=PARTITION_KEY, componentIndex=4, droppedAt=-9223372036854775808}, ColumnDefinition{name=ck0, type=org.apache.cassandra.db.marshal.FloatType, kind=CLUSTERING_COLUMN, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=ck1, type=org.apache.cassandra.db.marshal.ByteType, kind=CLUSTERING_COLUMN, componentIndex=1, droppedAt=-9223372036854775808}, ColumnDefinition{name=ck2, type=org.apache.cassandra.db.marshal.TimestampType, kind=CLUSTERING_COLUMN, componentIndex=2, droppedAt=-9223372036854775808}, ColumnDefinition{name=col0, type=org.apache.cassandra.db.marshal.ByteType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=col1, type=org.apache.cassandra.db.marshal.DurationType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=col10, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=col11, type=org.apache.cassandra.db.marshal.UUIDType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=col12, type=org.apache.cassandra.db.marshal.BytesType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=col13, type=org.apache.cassandra.db.marshal.FloatType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=col2, type=org.apache.cassandra.db.marshal.SimpleDateType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=col3, type=org.apache.cassandra.db.marshal.FloatType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=col4, type=org.apache.cassandra.db.marshal.AsciiType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=col5, type=org.apache.cassandra.db.marshal.TupleType(org.apache.cassandra.db.marshal.TimestampType, org.apache.cassandra.db.marshal.SimpleDateType, org.apache.cassandra.db.marshal.LongType, org.apache.cassandra.db.marshal.BytesType, org.apache.cassandra.db.marshal.DurationType, org.apache.cassandra.db.marshal.AsciiType, org.apache.cassandra.db.marshal.ShortType), kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=col6, type=org.apache.cassandra.db.marshal.DurationType, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=col7, type=org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.TimeUUIDType), kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=col8, type=org.apache.cassandra.db.marshal.TupleType(org.apache.cassandra.db.marshal.FloatType, org.apache.cassandra.db.marshal.IntegerType, org.apache.cassandra.db.marshal.TimestampType, org.apache.cassandra.db.marshal.InetAddressType), kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}, ColumnDefinition{name=col9, type=org.apache.cassandra.db.marshal.UTF8Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={"enabled":"true","postimage":"false","preimage":"false","ttl":"86400"},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=b5d20b22-7fae-11ea-be51-000000000000,droppedColumns={},collections={636f6c37 : org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.TimeUUIDType)},indices={}]
```

2020/04/16 06:52:13 Watching changes from 1455 of 1455 total streams
panic: runtime error: index out of range [0] with length 0

goroutine 89 [running]:
github.com/gocql/gocql.readInt(...)
	/go/src/github.com/gocql/gocql/frame.go:322
github.com/gocql/gocql.readBytes(...)
	/go/src/github.com/gocql/gocql/marshal.go:1895
github.com/gocql/gocql.unmarshalTuple(0x78c620, 0xc0000ee080, 0x0, 0x0, 0x0, 0x6b3e80, 0xc013441420, 0x0, 0xc01073f9a0)
	/go/src/github.com/gocql/gocql/marshal.go:1917 +0x1217
github.com/gocql/gocql.Unmarshal(0x78c620, 0xc0000ee080, 0x0, 0x0, 0x0, 0x6b3e80, 0xc013441420, 0x0, 0x0)
	/go/src/github.com/gocql/gocql/marshal.go:166 +0xd56
github.com/gocql/gocql.scanColumn(0x0, 0x0, 0x0, 0xc00011f4ac, 0x3, 0xc0000e85e0, 0x15, 0xc00011f4b0, 0x4, 0x78c620, ...)
	/go/src/github.com/gocql/gocql/session.go:1341 +0x1b3
github.com/gocql/gocql.(*Iter).Scan(0xc0106cbb00, 0xc00095c680, 0x33, 0x58, 0x96b040)
	/go/src/github.com/gocql/gocql/session.go:1446 +0x2e2
github.com/gocql/gocql.(*Iter).MapScan(0xc0106cbb00, 0xc01073fde8, 0x7247ac)
	/go/src/github.com/gocql/gocql/helpers.go:411 +0x16c
main.processStream.func1(0xc000133260, 0xbf9e1e0744942771, 0xfffffffffb8b6027, 0x94d700, 0xc0000e8240, 0x19, 0xc0000bc380, 0xc0000faf00, 0xc00025abc0, 0x10, ...)
	/go/src/github.com/piodul/cdc-stressor/main.go:286 +0x306
created by main.processStream
	/go/src/github.com/piodul/cdc-stressor/main.go:252 +0xde

**Comment by piodul** [comment]
The issue was caused by a bug in the older version gocql driver. It panicked when trying to deserialize nil tuples. This was recently fixed. I updated the driver version and checked that the error does not occur anymore.
